baseURL = "https://tech.clayman.pro/"
languageCode = "en-us"
title = "Kirill Sumorokov"
theme = "m10c"

[params]
author = "Kirill Sumorokov"
description = "Python backend developer and DevOps enthusiast"

[[menu.main]]
  identifier = "cv"
  name = "CV"
  url = "/cv/"

[[params.social]]
  icon = "github"
  name = "My Github"
  url = "https://github.com/clayman083"

[markup]
  [markup.highlight]
    anchorLineNos = false
    codeFences = true
    guessSyntax = false
    hl_Lines = ""
    lineAnchors = ""
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = true
    style = "monokai"
    tabWidth = 4
